// import { Inter } from "next/font/google";
// import type { Metadata } from "next";
// import "./globals.css";
// import Header from "@/components/ui/Header";
// import Footer from "@/components/ui/Footer";
// import { CartProvider } from "@/context/CartContext";
// import { TotalAmountProvider } from "@/context/TotalAmountContext";
// import ChatbotIcon from "@/components/ui/chatbot";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
// {/*         <link rel="icon" href="/favicon.ico" /> */}
//         <title>{metadata.title}</title>
//         <meta name="description" content={metadata.description} />
//       </head>
//       <body className={inter.className}>
//         <CartProvider>
//           <TotalAmountProvider>
//             <Header />
//             <main className="p-4 md:p-8">{children}</main>
//             <ChatbotIcon />
//             <Footer />
//           </TotalAmountProvider>
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { CartProvider } from "@/context/CartContext";
import { TotalAmountProvider } from "@/context/TotalAmountContext";
import ChatbotIcon from "@/components/ui/chatbot";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <TotalAmountProvider>
            <Header />
            <main className="p-4 md:p-8">{children}</main>
            <ChatbotIcon />
            <Footer />
          </TotalAmountProvider>
        </CartProvider>
      </body>
    </html>
  );
}

