import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/Header"; // Adjust the import path if necessary
import Footer from "@/components/ui/Footer"; // Adjust the import path if necessary
import { CartProvider } from "@/context/CartContext"; // Import CartProvider
import { TotalAmountProvider } from "./TotalAmountContext/page"; // Import TotalAmountProvider
import ChatbotIcon from "@/components/ui/chatbot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" /> {/* Add your favicon here */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <CartProvider>
          <TotalAmountProvider>
            <Header />
            <main className="p-4 md:p-8">
              {children}
            </main>
            <ChatbotIcon />
            <Footer />
          </TotalAmountProvider>
        </CartProvider>
      </body>
    </html>
  );
}
